version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: newspaper-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/uploads

  frontend:
    build:
      context: ./frontend
    container_name: newspaper-frontend
    ports:
      - "5173:80" # Прокидываем порт 5173 на 80 порт внутри контейнера
    depends_on:
      - backend

  db:
    image: postgres:16.2
    container_name: newspaper-db
    environment:
      POSTGRES_USER: <your-postgres-username>
      POSTGRES_PASSWORD: <your-postgres-password>
      POSTGRES_DB: news_portal
    ports:
      - "5432:5432"
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data

  initializer:
    build:
      context: .
    container_name: post-article-initializer
    depends_on:
      - backend
    volumes:
      - ./post_requests.py:/post_requests.py
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./backend/uploads:/uploads # Добавлено монтирование папки с изображениями
    restart: "no"
    command: ["/wait-for-it.sh", "newspaper-backend:8081", "--timeout=30", "--", "python", "/post_requests.py"]

networks:
  default:
    driver: bridge
